name: nanopore_realdata_workflow
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - pip
  - kraken2
  - metabuli
  - minimap2
  - samtools
  - pigz
  - rsync
  - pyyaml
  - snakemake-minimal>=9,<10
  - coverage>=7.6
  - pytest>=8
  - python-build>=1.2
  - ruff>=0.12
  - pip:
      - snakemake-executor-plugin-slurm>=1.9,<2
